<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Account</name>
   <tag></tag>
   <elementGuidId>82c0aacc-5e01-4aa4-aefb-b092dbd296d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>dx-button.dx-button.dx-button-mode-contained.dx-widget.dx-button-has-icon.dx-button-has-text.dx-button-primary.dx-state-focused.dx-state-active > div.dx-button-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RESV-BTN_SOURCCE']/div/cbt/dx-button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Account&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1e5f8513-8787-44f7-9069-a733cdb4bcf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-button-content</value>
      <webElementGuid>31d619bb-d069-4dc2-8830-aa475bd9e64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>7da4f6d5-aaa3-47f4-a59e-95e4b901fe97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RESV-BTN_SOURCCE&quot;)/div[@class=&quot;dx-field-value&quot;]/cbt[1]/dx-button[@class=&quot;dx-button dx-button-mode-contained dx-widget dx-button-has-icon dx-button-has-text dx-button-primary dx-state-focused dx-state-active&quot;]/div[@class=&quot;dx-button-content&quot;]</value>
      <webElementGuid>b7827869-68e0-4335-a3b4-6a3ca45014db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RESV-BTN_SOURCCE']/div/cbt/dx-button/div</value>
      <webElementGuid>9fb2256d-beac-47f5-9c86-3fa9d522cde9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[29]</value>
      <webElementGuid>64f04466-ea61-42ee-a177-52c2e54202de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHINHAN VIETNAM'])[1]/preceding::div[7]</value>
      <webElementGuid>7a77bdc9-def0-425a-9138-018fbd1ca2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngx-dnd-item[3]/div/div/column-layout/div/div/core-layout/ngx-dnd-container/div/ngx-dnd-item/div/div/item-layout/div/div/div/cbt/dx-button/div</value>
      <webElementGuid>ee33411a-ccb0-46fc-b0e4-d47b04a08a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Account' or . = 'Account')]</value>
      <webElementGuid>a25416ad-0746-428c-9996-e2fec350a3e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
