<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save</name>
   <tag></tag>
   <elementGuidId>c90954c9-7bd6-48a5-8f9f-114650003bb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>dx-button.dx-button.dx-button-default.dx-button-mode-contained.dx-widget.dx-button-has-icon.dx-button-has-text.dx-state-focused.dx-state-active > div.dx-button-content > span.dx-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='module']/div[2]/div/toolbar/div/div[6]/dx-button/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Save&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f1f9aca5-7cdd-4898-af0a-deb4aba0d218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-button-text</value>
      <webElementGuid>321ce7e5-e58d-4c0f-9b5d-1a201d7314b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>1abd8886-1f9b-44a5-aad9-59d423c500aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module&quot;)/div[@class=&quot;module-content&quot;]/div[@class=&quot;module-toolbar btn-check&quot;]/toolbar[@class=&quot;execBtn_MT02&quot;]/div[@class=&quot;fw toolbar&quot;]/div[@class=&quot;btn-toolbar float-left&quot;]/dx-button[@class=&quot;dx-button dx-button-default dx-button-mode-contained dx-widget dx-button-has-icon dx-button-has-text dx-state-focused dx-state-active&quot;]/div[@class=&quot;dx-button-content&quot;]/span[@class=&quot;dx-button-text&quot;]</value>
      <webElementGuid>4791b1a9-86ce-416c-b7a3-bbac311424c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='module']/div[2]/div/toolbar/div/div[6]/dx-button/div/span</value>
      <webElementGuid>45d35727-61c8-412a-b228-e56d0e2c53cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Out'])[1]/following::span[1]</value>
      <webElementGuid>9bb08578-a90f-46c7-8b0b-ed31fca8d6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check In'])[1]/following::span[2]</value>
      <webElementGuid>8a85ba55-a919-4c12-b518-725e25c8aa9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[1]</value>
      <webElementGuid>414bd0f5-f9cd-443a-8284-42fa773075e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Searching...'])[2]/preceding::span[2]</value>
      <webElementGuid>9b3c047a-ff68-4925-bfaa-5a6b36ff4a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>607dc29d-3ac2-4ff2-9bb4-badef66a6482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/dx-button/div/span</value>
      <webElementGuid>5db95161-f459-4c38-b643-c888c5104225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>67d40a05-837e-4a25-84ed-d30ff733425d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
