<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__dx-toast-icon</name>
   <tag></tag>
   <elementGuidId>8af012ed-6772-4d3e-992f-d7428a0de94e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dx-toast-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.dx-toast-icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed578134-fcb5-4e37-a258-d2480adbfa17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-toast-icon</value>
      <webElementGuid>7017eb07-dfda-41e4-a187-36ba1db954ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;dx-viewport dx-theme-generic dx-theme-generic-typography dx-color-scheme-greenmist&quot;]/div[@class=&quot;dx-overlay dx-widget dx-visibility-change-handler dx-toast&quot;]/div[@class=&quot;dx-overlay-wrapper dx-toast-wrapper&quot;]/div[@class=&quot;dx-overlay-content dx-toast-error dx-toast-content dx-resizable&quot;]/div[@class=&quot;dx-toast-icon&quot;]</value>
      <webElementGuid>b981172d-6efe-42d8-be8d-964f32647541</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>f9a39b28-3d4c-4136-a464-2a058cdbf99e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
