<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Name  Name is required</name>
   <tag></tag>
   <elementGuidId>5aac88fe-b914-4e5d-a475-c9f3c3d3e641</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RESV-LAST_NAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RESV-LAST_NAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Name *Name is required !&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37e3a282-e8df-4ff5-96c7-8b25bf4ad330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-field</value>
      <webElementGuid>3a2b8b9c-70bb-481d-afd0-7de24285b43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RESV-LAST_NAME</value>
      <webElementGuid>6360f752-554e-4357-8bbb-caff632d7b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name  *Name is required !</value>
      <webElementGuid>9df46ca4-81b8-45f2-8313-288103afee34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RESV-LAST_NAME&quot;)</value>
      <webElementGuid>e8dd2e9c-a09f-4424-867a-7834aa3841ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='RESV-LAST_NAME']</value>
      <webElementGuid>744c274b-3b43-45bf-8c96-a75f004192ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dx-c1d7c465-e7d6-403e-3409-52b3977e6b1a']/div/div/core-layout/ngx-dnd-container/div/ngx-dnd-item/div/div/column-layout/div/div/core-layout/ngx-dnd-container/div/ngx-dnd-item/div/div/group-layout/div/core-layout/ngx-dnd-container/div/ngx-dnd-item/div/div/column-layout/div/div/core-layout/ngx-dnd-container/div/ngx-dnd-item/div/div/item-layout/div/div</value>
      <webElementGuid>6423e8b3-4843-4666-adf2-268f546e4572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guest Information'])[1]/following::div[10]</value>
      <webElementGuid>6c0d7f96-55bd-4fc7-afc7-2ea9dabc11ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moving Transaction'])[1]/following::div[26]</value>
      <webElementGuid>6de87925-b46d-46f3-a62d-0b392f868e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//column-layout/div/div/core-layout/ngx-dnd-container/div/ngx-dnd-item/div/div/item-layout/div/div</value>
      <webElementGuid>7e6f3691-a6dc-4b59-81be-0e568095a82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'RESV-LAST_NAME' and (text() = 'Name  *Name is required !' or . = 'Name  *Name is required !')]</value>
      <webElementGuid>629cd882-2cdc-44b7-a52f-56cf04af78fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
