<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Address</name>
   <tag></tag>
   <elementGuidId>bab3ee21-f710-4efb-9850-eb1be1593cc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RESV-ADDRESS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RESV-ADDRESS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#RESV-ADDRESS</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>034c7f50-c45e-44af-a566-11bbdf7a4243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-field</value>
      <webElementGuid>ce06cef0-21a7-4a37-9f6f-b63feaf607b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RESV-ADDRESS</value>
      <webElementGuid>e5c86b2d-ef3a-4898-9531-041a7ea54ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Address </value>
      <webElementGuid>01af729c-fb73-4bbc-ac82-78ebede815f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RESV-ADDRESS&quot;)</value>
      <webElementGuid>f52746c0-aa16-485b-93b2-520a74a586fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='RESV-ADDRESS']</value>
      <webElementGuid>2b54ecd9-a5ad-491f-8d5d-7fafc13653df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dx-c1d7c465-e7d6-403e-3409-52b3977e6b1a']/div/div/core-layout/ngx-dnd-container/div/ngx-dnd-item/div/div/column-layout/div/div/core-layout/ngx-dnd-container/div/ngx-dnd-item/div/div/group-layout/div/core-layout/ngx-dnd-container/div/ngx-dnd-item/div/div/column-layout/div/div/core-layout/ngx-dnd-container/div/ngx-dnd-item[2]/div/div/item-layout/div/div</value>
      <webElementGuid>2d62d17e-2fa7-4f75-8464-e2f54a5d8b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name is required !'])[1]/following::div[9]</value>
      <webElementGuid>18d8c687-b64d-40f5-a37f-6ee86b7f4907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[20]</value>
      <webElementGuid>34125250-8097-4ff2-8448-7d4ba70bd062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/preceding::div[14]</value>
      <webElementGuid>6c513947-f7a8-462d-a73b-078d9f852beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngx-dnd-item[2]/div/div/item-layout/div/div</value>
      <webElementGuid>03a0d55a-bb80-4879-af78-58cc107d93ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'RESV-ADDRESS' and (text() = 'Address ' or . = 'Address ')]</value>
      <webElementGuid>8b41e7ff-bcdf-48ad-b101-e5d1d97acd58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
