<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Refreshing_RESV-RS_INFO</name>
   <tag></tag>
   <elementGuidId>437b2cde-6f1b-4a98-a65a-81ed61244567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RESV-RS_INFO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#RESV-RS_INFO</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b851f89e-5ccc-4a18-8a30-2d999a7e3a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-field</value>
      <webElementGuid>f6152112-8645-48bc-b223-d5ca616ee36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RESV-RS_INFO</value>
      <webElementGuid>799be6a0-84da-4dde-bbe2-a2027ff30155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RESV-RS_INFO&quot;)</value>
      <webElementGuid>1cf3ab87-7673-4c33-8a90-15f0691f9175</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='RESV-RS_INFO']</value>
      <webElementGuid>eefcadef-840c-4966-bed8-9b3c1892276c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='module']/div[2]/dx-scroll-view/div/div/div/div[2]/div/main-layout/div/div/core-layout/ngx-dnd-container/div/ngx-dnd-item/div/div/item-layout/div/div</value>
      <webElementGuid>bbcb9be5-3a70-4bea-b34a-1be9e7f8f9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refreshing...'])[1]/following::div[10]</value>
      <webElementGuid>422a7cee-89fc-42b8-9c29-22db183542fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release to refresh...'])[1]/following::div[11]</value>
      <webElementGuid>b5d39ceb-a42e-4183-87ad-c5583103fbcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Information'])[1]/preceding::div[9]</value>
      <webElementGuid>67f3524e-5968-4eac-b3b4-061328033d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing'])[1]/preceding::div[11]</value>
      <webElementGuid>1ae5635a-1a4f-4899-ba51-a0b3604fb5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//item-layout/div/div</value>
      <webElementGuid>a1c81677-4276-4358-ab7c-4f7c0abd8bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'RESV-RS_INFO']</value>
      <webElementGuid>98c8b93c-adbe-43f9-9039-753e77b5e1c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
