<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dx-texteditor-input</name>
   <tag></tag>
   <elementGuidId>8faf9aff-6735-4b10-ab2a-ba637c6de32e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.dx-texteditor-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RESV-LAST_NAME']/div/cti/div/dx-text-box/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#RESV-LAST_NAME >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b68e866-7558-44ef-bb45-87f89a36920a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>363110c8-9468-4e29-b00f-0d01f385d79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-texteditor-input</value>
      <webElementGuid>8de9fbf6-d0ff-4d0b-9571-62d97da58695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3802e13-34ff-4857-9dc9-2f967fc394fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b6f2e36f-8c76-4dea-ad6e-2d0800e4db48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>39a92d69-1fdd-4da6-b9f3-47e8b7ab7d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a47c22e2-7a80-46dd-ad53-ad47ee0a3a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RESV-LAST_NAME&quot;)/div[@class=&quot;dx-field-value&quot;]/cti[1]/div[1]/dx-text-box[@class=&quot;dx-validator dx-visibility-change-handler dx-show-invalid-badge dx-textbox dx-texteditor dx-editor-outlined dx-widget dx-state-focused dx-state-hover&quot;]/div[@class=&quot;dx-texteditor-container&quot;]/div[@class=&quot;dx-texteditor-input-container&quot;]/input[@class=&quot;dx-texteditor-input&quot;]</value>
      <webElementGuid>b17651d7-e809-46f9-aaa4-2d78f42ff935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>a5d2936d-b28f-4ea8-914f-80e6189b57b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RESV-LAST_NAME']/div/cti/div/dx-text-box/div/div/input</value>
      <webElementGuid>778640f3-edc4-46bc-8f3d-2e54afb1e458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>87f0f5e8-f2b1-4853-b91a-b8e717366c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>c43b46c7-a16b-4d0a-83df-20481d541f6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
