<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reservations</name>
   <tag></tag>
   <elementGuidId>7cd6d278-65b7-4c41-853a-1de1a1b249f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.menu-item.dx-template-wrapper.dx-item-content.dx-treeview-item-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Reservations' or . = 'Reservations')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Reservations&quot;i >> div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2210eb8c-76ed-4aa4-acf3-6b090434a334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item dx-template-wrapper dx-item-content dx-treeview-item-content</value>
      <webElementGuid>22e38127-2896-43fa-8d23-36f096153688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reservations</value>
      <webElementGuid>f0d02bd5-cca2-43a5-83ea-c77165b4294e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dx-3f59374c-fd48-2dd7-95d9-3bb7a6cd759f&quot;)/div[@class=&quot;dx-item dx-treeview-item dx-state-hover&quot;]/div[@class=&quot;menu-item dx-template-wrapper dx-item-content dx-treeview-item-content&quot;]</value>
      <webElementGuid>9f7f65a3-3556-4b68-8526-f5c14646d59c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='dx-3f59374c-fd48-2dd7-95d9-3bb7a6cd759f']/div/div</value>
      <webElementGuid>d5c0b3ee-4fb1-42ad-8754-2c24a04d3dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST01'])[1]/following::div[20]</value>
      <webElementGuid>18fca751-2be6-4401-ba35-933fc34fe5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PMS - Properties Management System'])[1]/following::div[34]</value>
      <webElementGuid>4beef263-de72-4dab-a6c9-0432dabd3eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Front Desk'])[1]/preceding::div[2]</value>
      <webElementGuid>917248dd-0c88-4f33-b411-94c0daecbf05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>62d88221-2e2f-4f52-a1c8-ad636f4dbdc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Reservations' or . = 'Reservations')]</value>
      <webElementGuid>3dd9be14-ab2f-4cbb-b983-60bcb13a244b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
