<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Save</name>
   <tag></tag>
   <elementGuidId>b20eecc0-e431-4205-8591-b25739670532</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>dx-button.dx-button.dx-button-default.dx-button-mode-contained.dx-widget.dx-button-has-icon.dx-button-has-text.dx-state-focused.dx-state-active > div.dx-button-content > span.dx-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='module']/div[2]/div/toolbar/div/div[6]/dx-button/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Save&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c18d647b-e6ca-46b3-9c36-d410294724f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-button-text</value>
      <webElementGuid>46d59d51-33d0-4de4-a4c6-d85a9baabced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>24d1a7c8-5fb5-4774-94d6-6301198e5c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module&quot;)/div[@class=&quot;module-content&quot;]/div[@class=&quot;module-toolbar btn-check&quot;]/toolbar[@class=&quot;execBtn_MT02&quot;]/div[@class=&quot;fw toolbar&quot;]/div[@class=&quot;btn-toolbar float-left&quot;]/dx-button[@class=&quot;dx-button dx-button-default dx-button-mode-contained dx-widget dx-button-has-icon dx-button-has-text dx-state-focused dx-state-active&quot;]/div[@class=&quot;dx-button-content&quot;]/span[@class=&quot;dx-button-text&quot;]</value>
      <webElementGuid>8ad0bd3d-d36c-4e91-9a01-a0bcb1a83a7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='module']/div[2]/div/toolbar/div/div[6]/dx-button/div/span</value>
      <webElementGuid>1e9c328f-d134-4b6a-9a3e-fa9138a64860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Out'])[1]/following::span[1]</value>
      <webElementGuid>83847414-3675-456d-b218-26246cc0695e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check In'])[1]/following::span[2]</value>
      <webElementGuid>43e140ff-cf2f-4a6c-a2a3-2ce740fee92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[1]</value>
      <webElementGuid>f4edadae-380f-4ae8-9af3-c206f2ae7d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Searching...'])[2]/preceding::span[2]</value>
      <webElementGuid>6cc83fee-313f-4e02-adaa-0414840e75f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>f61f3c16-1423-4d6d-8034-411d1e5c4a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/dx-button/div/span</value>
      <webElementGuid>f1b32c37-a4e9-409b-acc1-ad53e01a958d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>72eba289-78c4-4a04-bb62-0d047f2b71d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
