<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>data_Tentative</name>
   <tag></tag>
   <elementGuidId>341ee9c4-b382-40ee-bac6-57627b9fea71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[title=&quot;Tentative&quot;] > span.float-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Tentative' or . = 'Tentative')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Tentative&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2ca3c926-257f-449c-8236-d1cad7d50568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float-left</value>
      <webElementGuid>bbc80bd6-6e38-46e9-bfb1-ecbc3b1d370d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tentative</value>
      <webElementGuid>1231a731-da14-488f-949f-4935bd038ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dx-c8645d8d-2a05-4ded-4a42-88f069abc6b6&quot;)/div[@class=&quot;dx-scrollable-wrapper&quot;]/div[@class=&quot;dx-scrollable-container&quot;]/div[@class=&quot;dx-scrollable-content&quot;]/div[@class=&quot;dx-scrollview-content&quot;]/div[@class=&quot;dx-item dx-list-item dx-state-active&quot;]/div[@class=&quot;dx-template-wrapper dx-item-content dx-list-item-content&quot;]/div[1]/span[@class=&quot;float-left&quot;]</value>
      <webElementGuid>126a9a0e-9f1a-421f-aa22-e63216388536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dx-c8645d8d-2a05-4ded-4a42-88f069abc6b6']/div/div/div/div[2]/div/div/div/span</value>
      <webElementGuid>f938729c-ddef-41af-be94-9800d2fec92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refreshing...'])[5]/following::span[1]</value>
      <webElementGuid>ddd68ada-c677-4ea0-a330-091f2bd87e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release to refresh...'])[5]/following::span[1]</value>
      <webElementGuid>26c94b1c-3838-48ed-9323-b6df26ee1f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Definite'])[1]/preceding::span[1]</value>
      <webElementGuid>81fb6e26-4727-47d7-ad7c-f368ba6374ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waiting'])[1]/preceding::span[2]</value>
      <webElementGuid>1fc85625-19bd-405e-b78e-b80b038fe9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tentative']/parent::*</value>
      <webElementGuid>decd6af7-47af-423b-9f10-415c801376b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/div/div/span</value>
      <webElementGuid>f1224ab5-e6d1-4b6d-8bf9-b9a11451e37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tentative' or . = 'Tentative')]</value>
      <webElementGuid>5b4521fa-528b-44af-9b97-3ed497b77a43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
