<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tentative</name>
   <tag></tag>
   <elementGuidId>7be9df4a-40ae-4d12-b136-93cdce432422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[title=&quot;Tentative&quot;] > span.float-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dx-d72a45b7-f791-26f8-a299-b9d11232c9e6']/div/div/div/div[2]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Tentative&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>16d41c79-8a26-4cd4-9d5f-fd6e358c359d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float-left</value>
      <webElementGuid>04f36f85-e47c-4208-98f5-5eda636bac4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tentative</value>
      <webElementGuid>a347d3a0-ba64-4d53-93f0-b92209e42fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dx-d72a45b7-f791-26f8-a299-b9d11232c9e6&quot;)/div[@class=&quot;dx-scrollable-wrapper&quot;]/div[@class=&quot;dx-scrollable-container&quot;]/div[@class=&quot;dx-scrollable-content&quot;]/div[@class=&quot;dx-scrollview-content&quot;]/div[@class=&quot;dx-item dx-list-item dx-state-active&quot;]/div[@class=&quot;dx-template-wrapper dx-item-content dx-list-item-content&quot;]/div[1]/span[@class=&quot;float-left&quot;]</value>
      <webElementGuid>03256e40-ebf3-48a6-977a-3d8ef1f35207</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dx-d72a45b7-f791-26f8-a299-b9d11232c9e6']/div/div/div/div[2]/div/div/div/span</value>
      <webElementGuid>46825403-e3f7-4973-a9df-a2b27b760075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refreshing...'])[4]/following::span[1]</value>
      <webElementGuid>57f18b86-b89a-491a-8983-37f782265bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release to refresh...'])[4]/following::span[1]</value>
      <webElementGuid>52ac1cd9-5394-4004-87a1-9d5ca4bbb8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Definite'])[1]/preceding::span[1]</value>
      <webElementGuid>d44adbca-bd2f-4e73-bb62-5b4421bd14e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waiting'])[1]/preceding::span[2]</value>
      <webElementGuid>b1f31950-d32b-4d2e-9742-c863b5de9a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tentative']/parent::*</value>
      <webElementGuid>a52cfb7d-240b-48cd-9470-e9876c8233fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/div/div/span</value>
      <webElementGuid>e45b674b-1efa-40bc-bde9-a54e83845f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tentative' or . = 'Tentative')]</value>
      <webElementGuid>c4047ec0-cb0e-454b-8a81-e7465b91b8ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
