<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_29</name>
   <tag></tag>
   <elementGuidId>4068028f-154c-4e34-a3a6-cbdabc8afc31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.dx-calendar-cell.dx-state-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dx-243dd6d2-4caf-30e9-1fd3-7a0426477518']/div/div/div/div/table/tbody/tr[5]/td[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Friday, March 29, 2024&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>606951cc-845f-4d6f-8171-4a95f3c60fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-calendar-cell dx-state-active</value>
      <webElementGuid>93284b4f-ddba-4e67-b96e-829dd1117381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2024/03/29</value>
      <webElementGuid>3aaf379d-6d7e-45a7-a5e2-434620cc999c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>0cec9314-5b89-4638-a2c8-e48935e2e473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Friday, March 29, 2024</value>
      <webElementGuid>60d30968-b9db-4a66-b3dc-894540dd3c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>465630c3-d834-48dd-a664-47029b04e3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dx-243dd6d2-4caf-30e9-1fd3-7a0426477518&quot;)/div[@class=&quot;dx-show-invalid-badge dx-widget dx-visibility-change-handler dx-calendar dx-calendar-view-month dx-swipeable&quot;]/div[@class=&quot;dx-calendar-body&quot;]/div[@class=&quot;dx-calendar-views-wrapper&quot;]/div[@class=&quot;dx-widget dx-state-hover&quot;]/table[1]/tbody[1]/tr[5]/td[@class=&quot;dx-calendar-cell dx-state-active&quot;]</value>
      <webElementGuid>77645b7f-d2e4-4bfa-9acb-41a6ba019836</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dx-243dd6d2-4caf-30e9-1fd3-7a0426477518']/div/div/div/div/table/tbody/tr[5]/td[6]</value>
      <webElementGuid>6496453b-e4e2-4edc-bafe-ff6aca7e350f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::td[34]</value>
      <webElementGuid>d23cb020-d770-437e-9cc2-a5b0dcda13fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::td[34]</value>
      <webElementGuid>68f2f4dc-a1a5-4002-8756-0a92f31122fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[2]/preceding::td[9]</value>
      <webElementGuid>33acbfd4-6258-4026-a152-816098be84b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[2]/preceding::td[9]</value>
      <webElementGuid>c5241bc8-d57a-4e73-a7c4-a9ec79d90e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[6]</value>
      <webElementGuid>7c152a7d-bfa7-4e3c-af44-a0d456be8135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '29' or . = '29')]</value>
      <webElementGuid>91e9d844-1091-4b1f-a673-e2415b33ad19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
