<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login</name>
   <tag></tag>
   <elementGuidId>b9244c49-7b55-453b-a964-1ecb0f5cfe3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dx-button-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In to your account'])[1]/following::div[14]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Login&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>770ce4bb-a8d5-4287-8357-b5d06c9e88d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-button-content</value>
      <webElementGuid>583c0645-d6d2-4337-bfc8-6c1c692c3a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>c0e084dc-5a66-4a81-8028-1a256f3bb793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;dx-viewport dx-theme-generic dx-theme-generic-typography dx-color-scheme-greenmist&quot;]/app-root[@class=&quot;screen-medium&quot;]/app-single-card[1]/dx-scroll-view[@class=&quot;full-height-scrollable dx-scrollable dx-scrollview dx-visibility-change-handler dx-scrollable-vertical dx-scrollable-simulated&quot;]/div[@class=&quot;dx-scrollable-wrapper&quot;]/div[@class=&quot;dx-scrollable-container&quot;]/div[@class=&quot;dx-scrollable-content&quot;]/div[@class=&quot;dx-scrollview-content&quot;]/div[@class=&quot;dx-card content&quot;]/app-login-form[1]/dx-validation-group[@class=&quot;dx-validationgroup&quot;]/div[@class=&quot;dx-field&quot;]/dx-button[@class=&quot;dx-button dx-button-default dx-button-mode-contained dx-widget dx-button-has-text dx-state-focused dx-state-active&quot;]/div[@class=&quot;dx-button-content&quot;]</value>
      <webElementGuid>230ab5f1-e59d-46d7-98f1-257d3d5fd820</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In to your account'])[1]/following::div[14]</value>
      <webElementGuid>3930a26a-650f-4d9c-8e45-b7416f838a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refreshing...'])[1]/following::div[20]</value>
      <webElementGuid>11f7bea6-525b-4514-b942-876cb2552e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::div[14]</value>
      <webElementGuid>8422cb24-1bf3-434d-b808-359a9c599c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dx-button/div</value>
      <webElementGuid>efc3c6af-69dd-4afd-91ff-140f9d39b29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>31fba98a-b5d7-4e00-8866-12841912aeb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
