<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BAR3</name>
   <tag></tag>
   <elementGuidId>dd8c8ee0-a315-4987-82be-0f21d466014e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dx-item.dx-list-item.dx-state-active > div.dx-template-wrapper.dx-item-content.dx-list-item-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dx-a6eae9c8-5a31-3487-143e-672d397092b6']/div/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;_ BAR3&quot;i] >> div >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73b1d4e5-394a-4a65-9c3d-3b8564708228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-template-wrapper dx-item-content dx-list-item-content</value>
      <webElementGuid>77b5bd2c-a1b5-4b92-a065-978974d2fc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BAR3</value>
      <webElementGuid>1b9f348f-2c68-4a90-b501-35d74f78c17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dx-a6eae9c8-5a31-3487-143e-672d397092b6&quot;)/div[@class=&quot;dx-scrollable-wrapper&quot;]/div[@class=&quot;dx-scrollable-container&quot;]/div[@class=&quot;dx-scrollable-content&quot;]/div[@class=&quot;dx-scrollview-content&quot;]/div[@class=&quot;dx-item dx-list-item dx-state-active&quot;]/div[@class=&quot;dx-template-wrapper dx-item-content dx-list-item-content&quot;]</value>
      <webElementGuid>187f6faf-e689-443f-8482-0bfc96a4c772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dx-a6eae9c8-5a31-3487-143e-672d397092b6']/div/div/div/div[2]/div/div</value>
      <webElementGuid>865076a1-45cd-4b4a-9638-aa5a5f4dea1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refreshing...'])[6]/following::div[3]</value>
      <webElementGuid>51880595-f6fb-4969-a0ae-be1b6b907064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release to refresh...'])[6]/following::div[4]</value>
      <webElementGuid>45b70b3f-f77f-4520-ae63-c8ca71d29b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAR2'])[1]/preceding::div[2]</value>
      <webElementGuid>6bded4fe-cef3-45da-9a1e-7329d25f7e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>c318e44a-5ba3-4917-897d-dcae13288644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'BAR3' or . = 'BAR3')]</value>
      <webElementGuid>67f1f861-8d51-4843-b108-ffe3b5f259da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
