<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Reserve</name>
   <tag></tag>
   <elementGuidId>90f22068-c7c9-435f-b1fc-967ed8320547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>dx-button.dx-button.dx-button-default.dx-button-mode-contained.dx-widget.dx-button-has-icon.dx-button-has-text.dx-state-focused.dx-state-active > div.dx-button-content > span.dx-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='module']/div[2]/div/toolbar/div/div[2]/dx-button/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Reserve&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c024956-971c-4167-b5d3-9709c52c5c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-button-text</value>
      <webElementGuid>0d86bbb9-2e39-4298-a1af-949d0df312db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reserve</value>
      <webElementGuid>6f496a8a-0e37-4ad7-95e4-2a9340e88d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module&quot;)/div[@class=&quot;module-content&quot;]/div[@class=&quot;module-toolbar btn-check&quot;]/toolbar[@class=&quot;execBtn_MT02&quot;]/div[@class=&quot;fw toolbar&quot;]/div[@class=&quot;btn-toolbar float-left&quot;]/dx-button[@class=&quot;dx-button dx-button-default dx-button-mode-contained dx-widget dx-button-has-icon dx-button-has-text dx-state-focused dx-state-active&quot;]/div[@class=&quot;dx-button-content&quot;]/span[@class=&quot;dx-button-text&quot;]</value>
      <webElementGuid>53e1eed4-9130-49b9-a5cd-d8f89fee4b34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='module']/div[2]/div/toolbar/div/div[2]/dx-button/div/span</value>
      <webElementGuid>137fe319-68f7-4ab9-ab17-239a942eb1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/following::span[1]</value>
      <webElementGuid>6de50b4c-1e08-4c6e-a9b6-a929d5d46359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[6]/following::span[2]</value>
      <webElementGuid>e56e8354-69dd-4e68-bce4-9ce70c02f9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[1]</value>
      <webElementGuid>644cf49f-bcd9-4a1e-a99f-faf08753dd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[7]/preceding::span[2]</value>
      <webElementGuid>7c345ed3-d8bf-48b1-af0a-c2fa12e2754a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reserve']/parent::*</value>
      <webElementGuid>8a0611c8-ac12-4417-83b1-e85b0a1ef72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/dx-button/div/span</value>
      <webElementGuid>c491c08a-aeba-4add-a18a-88b761fe74bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Reserve' or . = 'Reserve')]</value>
      <webElementGuid>9654d998-0da6-47d1-a41a-94366839b394</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
